### ISSUE TITLE
Localisation problème

### ISSUE THREAD

**Issue by daffypenelope** [year-calendar/js-year-calendar#13]
Bonjour,
En utilisant les configurations locales, je voulais commencer les mois par un dimanche.
Cela ne fonctionne pas avec le lien direct https://unpkg.com/js-year-calendar@latest/locales/js-year-calendar.fr.js (weekStart: 1)
Par contre si je modifie weekStart: 0 dans le fichier js-year-calendar.fr.js par exemple, tout est OK.
Why?

**Comment by Paul-DS** [comment]
Si le paramètre `weekStart` n'est pas spécifié, la librairie utilise le paramètre du fichier locale utilisé. La locale française spécifie que la semaine commence par un lundi.

Dans ton cas tu souhaite overrider le paramètre par défaut de la locale (Lundi) pour le remplacer par le tien (Dimanche). Donc il faut en effet spécifier directement le paramètre `weekStart` dans l'initialisation du calendrier.

Dans le futur essaye d'utiliser l'anglais plutôt que le français dans les échanges sur GitHub, afin que tout le monde puisse relire/participer.
