### ISSUE TITLE
alwaysHalfDay not always working?

### ISSUE THREAD

**Issue by iansheldon** [year-calendar/js-year-calendar#17]
Hi,

Thanks for creating such an awesome calendar.  

I have a calendar set to autoHalfDay:'true' but it randomly carries this instruction out.  Sometimes it works and sometimes it doesn't.

I have attached a screen shot of the example.  The data is pulled in from a JSON source.

It appears that sometimes the relevant classes are added to the first and last days of an event, and other times they are not, but at the moment I cannot work out a pattern.

<img width="896" alt="Screenshot 2019-10-17 at 10 51 27" src="https://user-images.githubusercontent.com/56677258/66998443-2ec27000-f0cc-11e9-9aaa-104db2f9d9fc.png">

```
let tooltip = null;

			const calendar = new Calendar('#yearcalendar', {
			  dataSource: function(year) {
				return fetch('scripts/_getyearbookings.php?token=<?php echo ($rsproperty->getColumnVal("property_token")); ?>')
				  .then(result => result.json())
				  .then(result => {
					if (result) {
					  return result.map(r => ({
						startDate: new Date(r.start),
						endDate: new Date(r.end),
						name: r.title,
						color: r.color,
						url: r.url,
						endHalfDay: r.endHalfDay,
						startHalfDay: r.startHalfDay
					  }));
					}

					return [];
				  });
			  },
			  clickDay: function(e){
			    window.open(e.events[0].url, '_self');
		      },
			  mouseOnDay: function(e) {
				if (e.events.length > 0) {
				  var content = '';

				  for (var i in e.events) {
					content += '<div class="event-tooltip-content">'
					  + '<div class="event-name" style="color:' + e.events[i].color + '">' + e.events[i].name + '</div>'	  
					  + '</div>';
				  }

				  if (tooltip !== null) {
					tooltip.destroy();
					tooltip = null;
				  }

				  tooltip = tippy(e.element, {
					  placement: 'right',
					  content: content,
					  animateFill: false,
					  animation: 'shift-away',
					  arrow: true
				  });
				  tooltip.show();
				}
			  },
			  mouseOutDay: function() {
				if (tooltip !== null) {
				  tooltip.destroy();
				  tooltip = null;
				}
			  },
			  style:'background',
			  Overlap:'true',
			  autoHalfDay:'true'
```

Is there anything I can check to fix this?

Thanks!
Ian

**Comment by western3021** [comment]
Hi!
I'm encountering the same issue : did you solved it ? 
Thanxxxx

**Comment by AndrejGrbin** [comment]
Hi,
I'm also struggling with it. It has something with date format but I don't know how to solve it.
Because if you manually write date as string, for ex. like this:
 startDate: new Date("yyyy-mm-dd"), 
it also doesn't work with alwaysHalfDay.
But if you write it with commas like this:
 startDate: new Date(yyyy, mm, dd),
it does.
Someone pleeease..
