### ISSUE TITLE
Offset in month of  date

### ISSUE THREAD

**Issue by JoanPortell** [year-calendar/js-year-calendar#24]
On examples and in use:

new Calendar('#calendar', {
  dataSource: [
    { startDate: new Date(currentYear, 2, 1), endDate: new Date(currentYear, 2, 10) },
    { startDate: new Date(currentYear, 2, 5), endDate: new Date(currentYear, 2, 15) }
  ],
  enableRangeSelection: true
})

and days  in calendar .. see image: (month = 3 not 2)

![sense nom](https://user-images.githubusercontent.com/59936994/73067281-8c730f00-3ea8-11ea-88fa-1025ce164a22.jpg)

**Comment by FireEmerald** [comment]
That's not a bug it's the normal behavior.

Read the documentation of the Date constructor: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

> **monthIndex**
> _Integer value representing the month, beginning with 0 for January to 11 for December._
