### ISSUE TITLE
Idea Create New Type of calendar (Only one month)

### ISSUE THREAD

**Issue by GorlikItsMe** [year-calendar/js-year-calendar#26]
I have idea, Create type of calendar where you can display only one month not 12. What do you think about that?
PS Good job, Your calendar is fantastic

**Comment by Paul-DS** [comment]
Thank you for your feedback.
This widget has been made specifically for displaying an entire year. There are other library that can be used to display one/several months (like this one: https://github.com/dangrossman/daterangepicker). Would it be a good fit for your need ?

You are not the first one asking for this feature, so I propose to use this issue to keep track of all users who would like this functionality, and I'll see if we have many people asking for it.

**Comment by Paul-DS** [comment]
This feature will be available in a future version, you can follow the development in the PR #32

**Comment by ponchautf** [comment]
Hi, did you have an plan when this feature will be available?

**Comment by Paul-DS** [comment]
The feature is available in v2.0.0. Check the options `startDate` and `numberMonthsDisplayed` in the [documentation](https://year-calendar.github.io/js-year-calendar/documentation)
