### ISSUE TITLE
ContextMenuItems out of screen

### ISSUE THREAD

**Issue by juanramonmartinez** [year-calendar/js-year-calendar#28]
Hi.

Congrats for this awesome calendar.

When you have context menu items, if you make left click in days shown on the right, these contexts menus are displayed out of the screen.

Is there any posibility to open the context menu over left direcction in these cases?

![img-a](https://user-images.githubusercontent.com/37975911/77854476-e2d33580-71ea-11ea-87a4-539499570f3e.png)

![img-b](https://user-images.githubusercontent.com/37975911/77854479-e8c91680-71ea-11ea-89ab-19909816a96e.png)

In your examples:

![img-c](https://user-images.githubusercontent.com/37975911/77854577-58d79c80-71eb-11ea-9bec-9c7d6804e393.png)

** Sorry for my English.

**Comment by Paul-DS** [comment]
Thank you for your feedback.

I fixed this issue, you can try it in the version `1.0.2-alpha.1`.

If you use NPM, you can install this version using `npm install js-year-calendar@next`
If you use the CDN, you can use this version using https://unpkg.com/js-year-calendar@next/dist/js-year-calendar.min.js

**Comment by juanramonmartinez** [comment]
Many Thanks. It works perfect!!!

**Comment by Paul-DS** [comment]
I published the version 1.0.2, so you can stop using the @next version.

**Comment by juanramonmartinez** [comment]
OK.

Thanks!!



________________________________
De: Paul-DS <notifications@github.com>
Enviado: domingo, 5 de abril de 2020 14:06
Para: year-calendar/js-year-calendar <js-year-calendar@noreply.github.com>
Cc: juanramonmartinez <jrmc_77@hotmail.com>; State change <state_change@noreply.github.com>
Asunto: Re: [year-calendar/js-year-calendar] ContextMenuItems out of screen (#28)


I published the version 1.0.2, so you can stop using the @next<https://github.com/next> version.
