### ISSUE TITLE
Data Source date shifted by one month

### ISSUE THREAD

**Issue by linkinstreet** [year-calendar/js-year-calendar#29]
Hi, I was trying out year-calendar when I realised the dates that I specified on my data source were shifted by +1 month. At first I thought it was my own rogue codes, but then I noticed it also happened with the example on that was posted and linked on the codepen.io site

![date](https://user-images.githubusercontent.com/9105806/78128932-54102400-7449-11ea-8267-88ffb9288df9.PNG)

here you can see the example dates are shifted, instead of October and November, it now moves to November and December.

**Comment by Paul-DS** [comment]
I let you see #24 

> That's not a bug it's the normal behavior.
> 
> Read the documentation of the Date constructor: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
> 
> > **monthIndex**
> > _Integer value representing the month, beginning with 0 for January to 11 for December._
