### ISSUE TITLE
Delete/Update function not firing on delete/update right clicked

### ISSUE THREAD

**Issue by 09wattry** [year-calendar/js-year-calendar#3]
I am using a Mac mouse and it has a single click button. When opening the context menu and trying to delete I cannot get these events to fire and call the functions. I'm not sure if this is a symptom of the mouse or a bug.

**Comment by 09wattry** [comment]
I have tested a few coworkers machines and it seems that there is an issue with the context menu staying open.

**Comment by Paul-DS** [comment]
I implemented a clean fix for this problem, thank you for your PR anyway.
It should be fixed in version 1.0.0-alpha.7 (you can try it here: https://codepen.io/Paul-DS/pen/EMWBYQ).
I tested on Windows and Linux, I let you test on MacOs.

Thank you for your feedback !
