### ISSUE TITLE
Change starting month for school year view

### ISSUE THREAD

**Issue by realservants-jeffrey** [year-calendar/js-year-calendar#30]
I'm wanting to use the full calendar view, but show the months for a school year.

So it would start on August 2020 and end July 2021.

**Comment by Paul-DS** [comment]
This feature will be available in a future version, you can follow the development in the PR #32

**Comment by Paul-DS** [comment]
The feature is available in v2.0.0. Check the options `startDate` and `numberMonthsDisplayed` in the [documentation](https://year-calendar.github.io/js-year-calendar/documentation)
