### ISSUE TITLE
Can we mark current date as selected on js year calendar

### ISSUE THREAD

**Issue by BhushanLaddha** [year-calendar/js-year-calendar#36]
I have gone through the different events provided and we can use all events easily.but I am facing challenges while marking current date as default selected.
I found one event setCustomDayRenderer but I am not getting how to implement that event in angular component.
Thanks in advance for your help.

**Comment by Paul-DS** [comment]
Yes you can use the customDayRenderer.
This is an example:
```
new Calendar('#calendar', {
  customDayRenderer: (element, date) => {
    if (date.getFullYear() == new Date().getFullYear() && date.getMonth() == new Date().getMonth() && date.getDate() == new Date().getDate()) {
      element.style.backgroundColor = "red";
    }
  }
})

```

Just replace the `element.style.backgroundColor = "red";` by the style or the CSS class you want to apply.

**Comment by BhushanLaddha** [comment]
Thank you for your quick response.i have implemented code changes suggested by you and it is working for me now.
