### ISSUE TITLE
Angular Compilation fails, unresolved references to interfaces from .d.ts file in dist

### ISSUE THREAD

**Issue by contactipraju** [year-calendar/js-year-calendar#6]
Trying to use this in my Angular 7 project, and followed these steps:

Installation:
_npm install js-year-calendar_
package.json now has the entry: "js-year-calendar": "^1.0.0-alpha.6"
Also included styles as: "node_modules/js-year-calendar/dist/js-year-calendar.css" in angular.json file.

Initialization:
_import Calendar from 'js-year-calendar'_

Usage:
_new Calendar('.calendar')_

But, the project **compilation fails**, as it cannot find the 7 interfaces that the dist/js-year-calendar.d.ts file refers to.  Is the dist folder supposed to have the interfaces copied as part of the compilation of the library?

Note: Only when I manually copy the interfaces into the dist folder, the compilation was successful; but I know that's not the way to fix it.

Please help.
Thanks

**Comment by Paul-DS** [comment]
I updated the build process to automatically generate all the d.ts files.

It should be fixed in version 1.0.0-alpha.7.

Thank you for your feedback !
