### ISSUE TITLE
Custom Background Color does not work in Safari

### ISSUE THREAD

**Issue by csaggo** [year-calendar/js-year-calendar#60]
When setting a datasource like this:

`{startDate:new Date('2021-08-29 00:00:00'),endDate:new Date('2021-09-12 00:00:00'),color:'#57B030'}`

it gets rendered in Chrome and FF like expectet (style setting is 'background')

`<td class="day day-start" style="background-color: rgb(87, 176, 48);"><div class="day-content">29</div></td>`

but in safari the output is this:

`<td class="day"><div class="day-content">29</div></td>`

so the background color is missing.

**Comment by csaggo** [comment]
now reading my own post, i notice "day-start" class is missing to. So it seems the datasource is ignored alltogether.

i am loading it like so:

`new Calendar("#calendar-winter",{style:'background',dataSource:winterCalendarData,enableContextMenu:!1,language:'de',startYear:2021,})`

**Comment by csaggo** [comment]
oh man its solved, ignore all of the above. new Date was accepted in ff and chrome, but safari was more strict, works with new Date('2021-09-12')

**Comment by aledmb** [comment]
hello @csaggo!

did you manage to make this work by using only the date without the time component, as below?

`new Date('2021-09-12')`

it does not work in "background" style for me.
