### ISSUE TITLE
In a clean installation, how I can set Language?

### ISSUE THREAD

**Issue by regorodrijl** [year-calendar/js-year-calendar#66]
I have a clean installation in pure js.  I imported cdn from js and css like the "get started guide" references here: https://year-calendar.github.io/js-year-calendar/getstarted

When I initialize the Object Calendar. 
` $(document).ready(function() {
const calendario = new Calendar('#calendar', {
              enableRangeSelection: true,
              selectRange: function(e) {
                  console.log({ startDate: e.startDate, endDate: e.endDate });
              },
              language: 'es'
       }); });`

The language of the calendar doesn't change, If i execute  calendario.getLanguage(), the console returns "en".

How I can solve the problem? what is wrong?

Thanks

**Comment by Paul-DS** [comment]
You need to import the locale file. Please check the [Language section in the readme](https://github.com/year-calendar/js-year-calendar#language).

**Comment by regorodrijl** [comment]
Hi! thanks, to answer and solve my problem.
