### ISSUE TITLE
Interaction of alwaysHalfDay=true, allowOverlap=false

### ISSUE THREAD

**Issue by cabintech** [year-calendar/js-year-calendar#8]
When always using half days, then is should be possible for the end of one event to be the same day as the start of another (conceptually each occupies half of that day). Exactly 1 day of overlap should be allowed for adjacent events. But the range selection does not allow it in this case.

So if for example I have a rental house with one guest checking out in the morning and another checking in the afternoon then I cannot model it with these settings because the 2 ranges are not allowed to end/start on the same day.

In this case, overlap of (no more than) 1 day should be allowed.

**Comment by Paul-DS** [comment]
Should be fixed in version 1.0.0-alpha.7.

Thank you for your feedback !
