### ISSUE TITLE
js-year-calendar cannot support IE

### ISSUE THREAD

**Issue by eyfas** [year-calendar/js-year-calendar#9]
Hi....
i want to ask...why js-year-calendar cannot display in IE?

Thank you.

**Comment by LeonidCherkashin** [comment]
Hi.

i I solved this problem with polyfill

add before code

`if (window.NodeList && !NodeList.prototype.forEach) {
    NodeList.prototype.forEach = function (callback, thisArg) {
        thisArg = thisArg || window;
        for (var i = 0; i < this.length; i++) {
            callback.call(thisArg, this[i], i, this);
        }
    };
}
(function () {

    if ( typeof window.CustomEvent === "function" ) return false;
  
    function CustomEvent ( event, params ) {
      params = params || { bubbles: false, cancelable: false, detail: null };
      var evt = document.createEvent( 'CustomEvent' );
      evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
      return evt;
     }
  
    window.CustomEvent = CustomEvent;
  })();` 

and replace the line

`{var n=new Event(e);for(var a in n.calendar=this,t)n[a]=t[a];return this.element.dispatchEvent(n),n}`

to

`{var n=new CustomEvent(e);for(var a in n.calendar=this,t)n[a]=t[a];return this.element.dispatchEvent(n),n}`

**Comment by Paul-DS** [comment]
I fixed the compatibility with Internet Explorer (at least for IE11).
You can try with the last version (1.0.0-alpha.7).

Thank you for your feedback !

**Comment by eyfas** [comment]
It's work...Thank you very much ! ;)
